### ISSUE TITLE
Recreating image: NAME is already taken (race condition)

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/terraform-provider-opennebula#116] opened 2021-04-24 11:55 UTC
When I want to recreate an image under a different terraform resource name, `terraform plan` says that it wants to destroy the image and create a new one, but `terraform apply` destroys the original image, but then fails to create the new one with

```
opennebula_image.terraimage: Destroying... [id=1286]
opennebula_image.terraimage1: Creating...
opennebula_image.terraimage: Still destroying... [id=1286, 10s elapsed]
opennebula_image.terraimage: Destruction complete after 10s

Error: OpenNebula error [ALLOCATE]: [one.image.clone] Error allocating a new image. NAME is already taken by IMAGE 1286.
```

There is probably a race condition somewhere, that the old image name is still present somewhere deep in ONe. When I run `terraform apply` once again few seconds later, it creates the image correctly. This is OpenNebula-5.12.0.3, and the image is defined as follows (originally as `terraimage`, I am trying to recreate it as `terraimage1`):

```
resource "opennebula_image" "terraimage1" {
    clone_from_image = 1229
    name             = "terraclone-f33"
    datastore_id     = 100
    persistent       = false
    permissions      = "660"
    group            = "tfgroup"
}
```

**Comment by jaypif** [comment] 2021-04-26 08:07
Hi  @Yenya 

It is possible that the OpenNebula database is not well refreshed between the 2 calls (destroy and create).

It seems that for the provider the destroy was OK but for some reason opennebula refuse the new image because it already exists.

The provider behavior is correct as it consider the image destroyed (image status is "DONE") before recreating it. It seems the issue is on opennebula side.

**Comment by Yenya** [comment] 2021-04-26 08:42
OK, @jaypif - thanks for verifying this. So should I close this issue and open a new issue with base OpenNebula/one ?

EDIT: created an issue in the base OpenNebula: https://github.com/OpenNebula/one/issues/5359

-Yenya

**Comment by jaypif** [comment] 2021-04-26 09:09
I close this issue as this is a race condition on ONE side

**Closed as completed** 2021-04-26 09:09 UTC

**Comment by Yenya** [comment] 2021-04-26 09:25
Thanks and sorry for creating the issue to the incorrect package.

**Comment by jaypif** [comment] 2021-04-26 09:42
don't be ;).
I prefer reading issues instead of the contrary. It means people use the provider and OpenNebula :)

**Comment by treywelsh** [comment] 2021-06-11 17:53
I read the discussion in  OpenNebula/one#5359 and then I did some tests.
The presence of the image after deletion is already tested in the provider via the `waitForImageState` image method.
I'm able to reproduce your problem stated above in this issue, but at first glance I didn't noticed any obvious problem in the provider.

It may be due to the fact that terraform parallelize operations by default, so I tried this:
`terraform apply -parallelism=1`
And this work without any problem.
