### ISSUE TITLE
resources updates not applied

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#63] opened 2020-10-08 10:47 UTC
Resource updates are marked as applied in the plan even when not applied on the cloud provider.
We don't handle if a part could be updated or not there is no check, and there is no documentation.

Here's the quote from a team member on the problem:
````
For some resources modified post-spawned VM like `tags` or in context params like`START_SCRIPT[_BASE64]`, 
the ONE provider indicates that changes has been applied with success but in fact, nothing appeared in Sunstone.

It should inform the user that this resource is immutable, 
or do a force-replaces to apply it effectively (like AWS do with `user_data`) instead of silently fail.
```

**Comment by ilhaan** [comment] 2020-10-13 06:15
Seeing the same issue

**Comment by jaypif** [comment] 2020-10-13 07:14
Hi,

Context update are not taken into account. 
Tags update work but not context change. context change are only possible during VM instantiation. You need to destroy and recreate the resource to apply your changes.

**Comment by Yenya** [comment] 2021-04-26 14:18
@jaypif - in newer OpenNebula releases (about 5.4+ or so) the context can be updated any time, even when the VM is running. Destroy and recreate is no longer needed. That said, the context is provided in form of an IDE CD, which does not support hotplug in Linux. So the guest cannot be notifed about the context change. But as soon as it mounts the context CD (or reboots inside the same qemu process - no undeploy/deploy is needed), the new context becomes visible. So it would be nice to have the context changes from terraform resource propagated into the ONe state.

My use case is especially the `SSH_PUBLIC_KEY` context variable: I want to have it configured beforehand, so that I can configure the VM with Ansible as soon as it is created by Terraform, but I cannot overwrite `/root/.ssh/authorized_keys` in Ansible, because the modification would get destroyed by the contextualization scripts after the reboot (or undeploy/deploy cycle). So when I want to modify the SSH authorized keys for the existing VMs, I have to do it on the ONe context level, which - for VMs created by terraform means doing it on terraform level.

**Comment by Th0masL** [comment] 2021-07-27 07:51
Hello,

I can confirm that the Context Update on running VMs now works from the OpenNebula UI, but this does not works from Terraform.

Sadly I don't code in Go so I doubt I will be able to implement a fix for this problem.

**Comment by MEGrimshaw** [comment] 2021-07-27 18:46
@jaypif Is there any guidance on the turn around time around this issue?
Thanks!

**Comment by jaypif** [comment] 2021-07-27 18:49
I cannot commit on an ETA as the maintenance of the provider is performed when we have some bandwidth to do it.

I hope it will be possible to have some time to take a deep view on it in the coming weeks.

I let you know.

Thanks

**Comment by MEGrimshaw** [comment] 2021-07-27 18:56
Thanks for the update @jaypif

**Closed as completed** 2022-07-27 00:11 UTC
